### ISSUE TITLE
append_tx was ramed in deliver_tx

### ISSUE THREAD

**Issue by silviucpp** [block-finance/cpp-abci#1]
In last tendermint protocol append_tx was ramed in deliver_tx

**Comment by mdyring** [comment]
Hi @silviucpp 

I am happy to receive a pull request for the above. :-)

There are also a couple of other changes to ABCI, so if you need to get something up and running quickly I'd recommend using gRPC instead of the socket based ABCI.

This also allows you to broadcast transactions via the gRPC endpoint in Tendermint.
